### ISSUE TITLE
Create requirements.txt

### ISSUE THREAD

**Issue by treighton** [jdavancens/idea-list#14]
pip freeze > requirements.txt (may req sudo)

This will output a txt doc with all the required packages and versions.

**Comment by jdavancens** [comment]
ooo good call

**Comment by treighton** [comment]
Are you using virtualenv? or system python? If you arent using virtualenv, then i may clone this project, spin up a new site in a virtualenv and go that way. Also i propose moving to gitlab (unlimited free private repo's)

**Comment by krismanaya** [comment]
We could move the project to my account, I have private git.

**Comment by jdavancens** [comment]
I am using virtualenv. Let me look into gitlab. I'm open to that.

**Comment by treighton** [comment]
i like gitlab a lot...

**Comment by treighton** [comment]
currently what packages are you using?

**Comment by jdavancens** [comment]
just django and psycopg

**Comment by jdavancens** [comment]
I might just do the $7 / mo plan. Let's stick with GitHub for this project. I'm teaching Kris a branching workflow right now.

**Comment by treighton** [comment]
sounds good, im not super worried about private repo's im just personally bias towards gitlab because thats where 90% of my other code is
